name: "Greet Contributors"
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  GreetCommitter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet Contributor"
        uses: ibakshay/greet-contributors-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}