  on:
    push:
      branches:
        - main
        - add-github-actions
  jobs:
    publish:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/download-artifact@v3
          with: # Download artifacts from build.yml hopefully
            name: build-folders
            path: |
              opcuaIIoT
              examples
              package.json
              create_certificates.js
        - run: ls opcuaIIoT